### PR TITLE
Data pirating

### PR DESCRIPTION
**Pull request by mairaalves**
Added a scrapy web crawler through Correios CEP website to collect location data.

### CODE REVIEW

**Comment by ebbauer** [comment]
hi, @mairaalves !
How are you doing?

I'm evaluating your test and noticed some changes that I'd like you to change:
- Your results are only returning the first records of each UF page. Could you change to get all records?
- Could you treat the content encoding?

Thanks! :smile:

**Comment by mairaalves** [comment]
> hi, @mairaalves !
> How are you doing?
> 
> I'm evaluating your test and noticed some changes that I'd like you to change:
> 
> * Your results are only returning the first records of each UF page. Could you change to get all records?
> * Could you treat the content encoding?
> 
> Thanks!

Hi, @ebbauer 
How are you?

Thanks for you comment on my pull request :) 
About the changes you requested:
 - The results actually contain all records from all UF, but since scrapy works asynchronously the records are not grouped together. If you scroll down the results a little bit you'll see all the records from all UF are there. 
 - Regarding the enconding, I'll work on it

**Comment by ebbauer** [comment]
@mairaalves thanks for the tip for scrolling down on the resultset. I haven't thought about that.

I could only get 50 records from Data-crawler for SC state filtering all the records ids that started with "SC-", but the correios website informs there are 322 records for this state alone. What am I doing wrong now? :thinking:

**Comment by mairaalves** [comment]
Hi @ebbauer,
In fact I was only getting the results for the first pages! Thanks for letting me know, I've already fixed it. Now the scrapper is collecting all the results from all the pages :)
I also changed the result encoding to utf-8, I figured that's what you meant.

If there's anything else I could do to improve my code, please let me know. Thanks for the feedback.

**Pull request merged**
